#pragma once

enum class SamFlag
{
    READ_PAIRED = 0x1,
    PROPER_PAIR = 0x2,
    READ_UNMAPPED = 0x4,
    MATE_UNMAPPED = 0x8,
    READ_REVERSE_STRAND = 0x10,
    MATE_REVERSE_STRAND = 0x20,
    FIRST_IN_PAIR = 0x40,
    SECOND_IN_PAIR = 0x80,
    NOT_PRIMARY_ALIGNMENT = 0x100,
    READ_FAILS_QUALITY_CHECKS = 0x200,
    DUPLICATE_READ = 0x400,
    SUPPLEMENTARY_ALIGNMENT = 0x800
};